name: Deploy Mediplus App to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Mediplus Image
        run: |
          IMAGE_URI=919586551458.dkr.ecr.us-east-1.amazonaws.com/mediplus:v1
          docker build -t mediplus:v1 .
          docker tag mediplus:v1 $IMAGE_URI
          docker push $IMAGE_URI

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_URI=919586551458.dkr.ecr.us-east-1.amazonaws.com/mediplus:v1
            docker pull $IMAGE_URI
            docker stop mediplus || true
            docker rm mediplus || true
            docker run -d -p 81:80 --name mediplus $IMAGE_URI
